import Image from 'next/image';

export const metadata = {
  title: 'Portofolio',
  // description: 'Generated by Next.js',
};

export default function Portofolio() {
  const cards = [
    {
      id: 1,
      title: 'SIMLABKAL',
      image: '/simlabkal.png',
      description:
        'Simlabkal is a digital platform for promoting and facilitating the exchange of knowledge and skills among local communities.',
    },
    {
      id: 2,
      title: 'This Blog',
      image: '/blog.png',
      description:
        'Gamification Academy is a platform that promotes and facilitates the development of gamified learning experiences for teachers and students.',
    },
    {
      id: 3,
      title: 'Landing Page MSE',
      image: '/mse.png',
      description:
        'Learning Management System is a web-based application for managing courses, assessments, and student progress.',
    },
    {
      id: 4,
      title: 'Landing Page Saebos',
      image: '/saebos.png',
      description:
        'Website is a digital platform for promoting and facilitating the exchange of knowledge and skills among local communities.',
    },
    {
      id: 5,
      title: 'Wedding Webiste',
      image: '/wedding.png',
      description:
        'Website is a digital platform for promoting and facilitating the exchange of knowledge and skills among local communities.',
    },
  ];

  return (
    <div className="flex justify-center gap-2 md:flex-wrap md:justify-between md:gap-0">
      {cards.map((card, key) => (
        <div
          key={key}
          className="mb-8 w-[240px] cursor-pointer rounded-lg shadow-md shadow-gray-400 transition delay-75 ease-in-out hover:scale-105"
        >
          <Image
            src={card.image}
            alt={card.title}
            width="240"
            height="80"
            className="h-[160px] w-[240px] rounded-t-lg"
          />
          <p className="border-t py-2 text-center text-sm font-bold text-slate-600 shadow-sm">
            {card.title}
          </p>
        </div>
      ))}

      {cards && cards.length % 2 === 1 && <div className="w-[240px]"></div>}
    </div>
  );
}
